package pojoandmapping;
// Generated 23 juin 2014 16:20:08 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Absenceshebdo generated by hbm2java
 */
public class Absenceshebdo  implements java.io.Serializable {


     private Integer idAbsence;
     private Semaine semaine;
     private Integer nbAbsence;
     private Integer nbPersAbs;
     private Set sabsentes = new HashSet(0);

    public Absenceshebdo() {
    }

    public Absenceshebdo(Semaine semaine, Integer nbAbsence, Integer nbPersAbs, Set sabsentes) {
       this.semaine = semaine;
       this.nbAbsence = nbAbsence;
       this.nbPersAbs = nbPersAbs;
       this.sabsentes = sabsentes;
    }
   
    public Integer getIdAbsence() {
        return this.idAbsence;
    }
    
    public void setIdAbsence(Integer idAbsence) {
        this.idAbsence = idAbsence;
    }
    public Semaine getSemaine() {
        return this.semaine;
    }
    
    public void setSemaine(Semaine semaine) {
        this.semaine = semaine;
    }
    public Integer getNbAbsence() {
        return this.nbAbsence;
    }
    
    public void setNbAbsence(Integer nbAbsence) {
        this.nbAbsence = nbAbsence;
    }
    public Integer getNbPersAbs() {
        return this.nbPersAbs;
    }
    
    public void setNbPersAbs(Integer nbPersAbs) {
        this.nbPersAbs = nbPersAbs;
    }
    public Set getSabsentes() {
        return this.sabsentes;
    }
    
    public void setSabsentes(Set sabsentes) {
        this.sabsentes = sabsentes;
    }




}


