package pojoandmapping;
// Generated 23 juin 2014 16:20:08 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Agent generated by hbm2java
 */
public class Agent  implements java.io.Serializable {


     private String matricAg;
     private Service service;
     private Statut statut;
     private String nomAg;
     private String prenAg;
     private String sexe;
     private String telAgent;
     private String fonction;
     private Date dateNaissance;
     private String situationMat;
     private String profession;
     private Integer soldePharmacie;
     private String cdPositAg;
     private Date datePosit;
     private String emailAg;
     private Boolean typeAgent;
     private Date datePriseService;
     private Set agtraitedemabses = new HashSet(0);
     private Set sabsentes = new HashSet(0);
     private Set authentifications = new HashSet(0);
     private Set agtraitedemconges = new HashSet(0);
     private Set autorisationabsences = new HashSet(0);
     private Set conges = new HashSet(0);

    public Agent() {
    }

	
    public Agent(String matricAg) {
        this.matricAg = matricAg;
    }
    public Agent(String matricAg, Service service, Statut statut, String nomAg, String prenAg, String sexe, String telAgent, String fonction, Date dateNaissance, String situationMat, String profession, Integer soldePharmacie, String cdPositAg, Date datePosit, String emailAg, Boolean typeAgent, Date datePriseService, Set agtraitedemabses, Set sabsentes, Set authentifications, Set agtraitedemconges, Set autorisationabsences, Set conges) {
       this.matricAg = matricAg;
       this.service = service;
       this.statut = statut;
       this.nomAg = nomAg;
       this.prenAg = prenAg;
       this.sexe = sexe;
       this.telAgent = telAgent;
       this.fonction = fonction;
       this.dateNaissance = dateNaissance;
       this.situationMat = situationMat;
       this.profession = profession;
       this.soldePharmacie = soldePharmacie;
       this.cdPositAg = cdPositAg;
       this.datePosit = datePosit;
       this.emailAg = emailAg;
       this.typeAgent = typeAgent;
       this.datePriseService = datePriseService;
       this.agtraitedemabses = agtraitedemabses;
       this.sabsentes = sabsentes;
       this.authentifications = authentifications;
       this.agtraitedemconges = agtraitedemconges;
       this.autorisationabsences = autorisationabsences;
       this.conges = conges;
    }
   
    public String getMatricAg() {
        return this.matricAg;
    }
    
    public void setMatricAg(String matricAg) {
        this.matricAg = matricAg;
    }
    public Service getService() {
        return this.service;
    }
    
    public void setService(Service service) {
        this.service = service;
    }
    public Statut getStatut() {
        return this.statut;
    }
    
    public void setStatut(Statut statut) {
        this.statut = statut;
    }
    public String getNomAg() {
        return this.nomAg;
    }
    
    public void setNomAg(String nomAg) {
        this.nomAg = nomAg;
    }
    public String getPrenAg() {
        return this.prenAg;
    }
    
    public void setPrenAg(String prenAg) {
        this.prenAg = prenAg;
    }
    public String getSexe() {
        return this.sexe;
    }
    
    public void setSexe(String sexe) {
        this.sexe = sexe;
    }
    public String getTelAgent() {
        return this.telAgent;
    }
    
    public void setTelAgent(String telAgent) {
        this.telAgent = telAgent;
    }
    public String getFonction() {
        return this.fonction;
    }
    
    public void setFonction(String fonction) {
        this.fonction = fonction;
    }
    public Date getDateNaissance() {
        return this.dateNaissance;
    }
    
    public void setDateNaissance(Date dateNaissance) {
        this.dateNaissance = dateNaissance;
    }
    public String getSituationMat() {
        return this.situationMat;
    }
    
    public void setSituationMat(String situationMat) {
        this.situationMat = situationMat;
    }
    public String getProfession() {
        return this.profession;
    }
    
    public void setProfession(String profession) {
        this.profession = profession;
    }
    public Integer getSoldePharmacie() {
        return this.soldePharmacie;
    }
    
    public void setSoldePharmacie(Integer soldePharmacie) {
        this.soldePharmacie = soldePharmacie;
    }
    public String getCdPositAg() {
        return this.cdPositAg;
    }
    
    public void setCdPositAg(String cdPositAg) {
        this.cdPositAg = cdPositAg;
    }
    public Date getDatePosit() {
        return this.datePosit;
    }
    
    public void setDatePosit(Date datePosit) {
        this.datePosit = datePosit;
    }
    public String getEmailAg() {
        return this.emailAg;
    }
    
    public void setEmailAg(String emailAg) {
        this.emailAg = emailAg;
    }
    public Boolean getTypeAgent() {
        return this.typeAgent;
    }
    
    public void setTypeAgent(Boolean typeAgent) {
        this.typeAgent = typeAgent;
    }
    public Date getDatePriseService() {
        return this.datePriseService;
    }
    
    public void setDatePriseService(Date datePriseService) {
        this.datePriseService = datePriseService;
    }
    public Set getAgtraitedemabses() {
        return this.agtraitedemabses;
    }
    
    public void setAgtraitedemabses(Set agtraitedemabses) {
        this.agtraitedemabses = agtraitedemabses;
    }
    public Set getSabsentes() {
        return this.sabsentes;
    }
    
    public void setSabsentes(Set sabsentes) {
        this.sabsentes = sabsentes;
    }
    public Set getAuthentifications() {
        return this.authentifications;
    }
    
    public void setAuthentifications(Set authentifications) {
        this.authentifications = authentifications;
    }
    public Set getAgtraitedemconges() {
        return this.agtraitedemconges;
    }
    
    public void setAgtraitedemconges(Set agtraitedemconges) {
        this.agtraitedemconges = agtraitedemconges;
    }
    public Set getAutorisationabsences() {
        return this.autorisationabsences;
    }
    
    public void setAutorisationabsences(Set autorisationabsences) {
        this.autorisationabsences = autorisationabsences;
    }
    public Set getConges() {
        return this.conges;
    }
    
    public void setConges(Set conges) {
        this.conges = conges;
    }




}


