package pojoandmapping;
// Generated 23 juin 2014 16:20:08 by Hibernate Tools 3.2.1.GA



/**
 * AgtraitedemcongeId generated by hbm2java
 */
public class AgtraitedemcongeId  implements java.io.Serializable {


     private String matricAg;
     private String numDemConge;

    public AgtraitedemcongeId() {
    }

    public AgtraitedemcongeId(String matricAg, String numDemConge) {
       this.matricAg = matricAg;
       this.numDemConge = numDemConge;
    }
   
    public String getMatricAg() {
        return this.matricAg;
    }
    
    public void setMatricAg(String matricAg) {
        this.matricAg = matricAg;
    }
    public String getNumDemConge() {
        return this.numDemConge;
    }
    
    public void setNumDemConge(String numDemConge) {
        this.numDemConge = numDemConge;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof AgtraitedemcongeId) ) return false;
		 AgtraitedemcongeId castOther = ( AgtraitedemcongeId ) other; 
         
		 return ( (this.getMatricAg()==castOther.getMatricAg()) || ( this.getMatricAg()!=null && castOther.getMatricAg()!=null && this.getMatricAg().equals(castOther.getMatricAg()) ) )
 && ( (this.getNumDemConge()==castOther.getNumDemConge()) || ( this.getNumDemConge()!=null && castOther.getNumDemConge()!=null && this.getNumDemConge().equals(castOther.getNumDemConge()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getMatricAg() == null ? 0 : this.getMatricAg().hashCode() );
         result = 37 * result + ( getNumDemConge() == null ? 0 : this.getNumDemConge().hashCode() );
         return result;
   }   


}


