package pojoandmapping;
// Generated 23 juin 2014 16:20:08 by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Agtraitedemconge generated by hbm2java
 */
public class Agtraitedemconge  implements java.io.Serializable {


     private AgtraitedemcongeId id;
     private Conge conge;
     private Agent agent;
     private Integer atraite;
     private Date dateTraitement;
     private Boolean avis;
     private String commentaire;

    public Agtraitedemconge() {
    }

	
    public Agtraitedemconge(AgtraitedemcongeId id, Conge conge, Agent agent) {
        this.id = id;
        this.conge = conge;
        this.agent = agent;
    }
    public Agtraitedemconge(AgtraitedemcongeId id, Conge conge, Agent agent, Integer atraite, Date dateTraitement, Boolean avis, String commentaire) {
       this.id = id;
       this.conge = conge;
       this.agent = agent;
       this.atraite = atraite;
       this.dateTraitement = dateTraitement;
       this.avis = avis;
       this.commentaire = commentaire;
    }
   
    public AgtraitedemcongeId getId() {
        return this.id;
    }
    
    public void setId(AgtraitedemcongeId id) {
        this.id = id;
    }
    public Conge getConge() {
        return this.conge;
    }
    
    public void setConge(Conge conge) {
        this.conge = conge;
    }
    public Agent getAgent() {
        return this.agent;
    }
    
    public void setAgent(Agent agent) {
        this.agent = agent;
    }
    public Integer getAtraite() {
        return this.atraite;
    }
    
    public void setAtraite(Integer atraite) {
        this.atraite = atraite;
    }
    public Date getDateTraitement() {
        return this.dateTraitement;
    }
    
    public void setDateTraitement(Date dateTraitement) {
        this.dateTraitement = dateTraitement;
    }
    public Boolean getAvis() {
        return this.avis;
    }
    
    public void setAvis(Boolean avis) {
        this.avis = avis;
    }
    public String getCommentaire() {
        return this.commentaire;
    }
    
    public void setCommentaire(String commentaire) {
        this.commentaire = commentaire;
    }




}


