package pojoandmapping;
// Generated 23 juin 2014 16:20:08 by Hibernate Tools 3.2.1.GA



/**
 * AgtraitedemabsId generated by hbm2java
 */
public class AgtraitedemabsId  implements java.io.Serializable {


     private String matricAg;
     private String numDemAbs;

    public AgtraitedemabsId() {
    }

    public AgtraitedemabsId(String matricAg, String numDemAbs) {
       this.matricAg = matricAg;
       this.numDemAbs = numDemAbs;
    }
   
    public String getMatricAg() {
        return this.matricAg;
    }
    
    public void setMatricAg(String matricAg) {
        this.matricAg = matricAg;
    }
    public String getNumDemAbs() {
        return this.numDemAbs;
    }
    
    public void setNumDemAbs(String numDemAbs) {
        this.numDemAbs = numDemAbs;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof AgtraitedemabsId) ) return false;
		 AgtraitedemabsId castOther = ( AgtraitedemabsId ) other; 
         
		 return ( (this.getMatricAg()==castOther.getMatricAg()) || ( this.getMatricAg()!=null && castOther.getMatricAg()!=null && this.getMatricAg().equals(castOther.getMatricAg()) ) )
 && ( (this.getNumDemAbs()==castOther.getNumDemAbs()) || ( this.getNumDemAbs()!=null && castOther.getNumDemAbs()!=null && this.getNumDemAbs().equals(castOther.getNumDemAbs()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getMatricAg() == null ? 0 : this.getMatricAg().hashCode() );
         result = 37 * result + ( getNumDemAbs() == null ? 0 : this.getNumDemAbs().hashCode() );
         return result;
   }   


}


