package pojoandmapping;
// Generated 23 juin 2014 16:20:08 by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Agtraitedemabs generated by hbm2java
 */
public class Agtraitedemabs  implements java.io.Serializable {


     private AgtraitedemabsId id;
     private Autorisationabsence autorisationabsence;
     private Agent agent;
     private Integer atraite;
     private Date dateTraitement;
     private Boolean avis;
     private String commentaire;

    public Agtraitedemabs() {
    }

	
    public Agtraitedemabs(AgtraitedemabsId id, Autorisationabsence autorisationabsence, Agent agent) {
        this.id = id;
        this.autorisationabsence = autorisationabsence;
        this.agent = agent;
    }
    public Agtraitedemabs(AgtraitedemabsId id, Autorisationabsence autorisationabsence, Agent agent, Integer atraite, Date dateTraitement, Boolean avis, String commentaire) {
       this.id = id;
       this.autorisationabsence = autorisationabsence;
       this.agent = agent;
       this.atraite = atraite;
       this.dateTraitement = dateTraitement;
       this.avis = avis;
       this.commentaire = commentaire;
    }
   
    public AgtraitedemabsId getId() {
        return this.id;
    }
    
    public void setId(AgtraitedemabsId id) {
        this.id = id;
    }
    public Autorisationabsence getAutorisationabsence() {
        return this.autorisationabsence;
    }
    
    public void setAutorisationabsence(Autorisationabsence autorisationabsence) {
        this.autorisationabsence = autorisationabsence;
    }
    public Agent getAgent() {
        return this.agent;
    }
    
    public void setAgent(Agent agent) {
        this.agent = agent;
    }
    public Integer getAtraite() {
        return this.atraite;
    }
    
    public void setAtraite(Integer atraite) {
        this.atraite = atraite;
    }
    public Date getDateTraitement() {
        return this.dateTraitement;
    }
    
    public void setDateTraitement(Date dateTraitement) {
        this.dateTraitement = dateTraitement;
    }
    public Boolean getAvis() {
        return this.avis;
    }
    
    public void setAvis(Boolean avis) {
        this.avis = avis;
    }
    public String getCommentaire() {
        return this.commentaire;
    }
    
    public void setCommentaire(String commentaire) {
        this.commentaire = commentaire;
    }




}


