package pojoandmapping;
// Generated 28 juin 2014 12:48:27 by Hibernate Tools 3.2.1.GA



/**
 * ArchiveConge generated by hbm2java
 */
public class ArchiveConge  implements java.io.Serializable {


     private String numDemConge;

    public ArchiveConge() {
    }

    public ArchiveConge(String numDemConge) {
       this.numDemConge = numDemConge;
    }
   
    public String getNumDemConge() {
        return this.numDemConge;
    }
    
    public void setNumDemConge(String numDemConge) {
        this.numDemConge = numDemConge;
    }




}


