package pojoandmapping;
// Generated 23 juin 2014 16:20:08 by Hibernate Tools 3.2.1.GA



/**
 * Authentification generated by hbm2java
 */
public class Authentification  implements java.io.Serializable {


     private String idCompt;
     private Agent agent;
     private String password;
     private String typeCompte;
     private Boolean bloque;

    public Authentification() {
    }

	
    public Authentification(String idCompt) {
        this.idCompt = idCompt;
    }
    public Authentification(String idCompt, Agent agent, String password, String typeCompte, Boolean bloque) {
       this.idCompt = idCompt;
       this.agent = agent;
       this.password = password;
       this.typeCompte = typeCompte;
       this.bloque = bloque;
    }
   
    public String getIdCompt() {
        return this.idCompt;
    }
    
    public void setIdCompt(String idCompt) {
        this.idCompt = idCompt;
    }
    public Agent getAgent() {
        return this.agent;
    }
    
    public void setAgent(Agent agent) {
        this.agent = agent;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getTypeCompte() {
        return this.typeCompte;
    }
    
    public void setTypeCompte(String typeCompte) {
        this.typeCompte = typeCompte;
    }
    public Boolean getBloque() {
        return this.bloque;
    }
    
    public void setBloque(Boolean bloque) {
        this.bloque = bloque;
    }




}


