package pojoandmapping;
// Generated 23 juin 2014 16:20:08 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Autorisationabsence generated by hbm2java
 */
public class Autorisationabsence  implements java.io.Serializable {


     private String numDemAbs;
     private Typeabsence typeabsence;
     private Agent agent;
     private Date dateDem;
     private Date dateDebutAbs;
     private Date dateFinAbs;
     private Date dateRetourEff;
     private String commentaire;
     private Set agtraitedemabses = new HashSet(0);

    public Autorisationabsence() {
    }

	
    public Autorisationabsence(String numDemAbs) {
        this.numDemAbs = numDemAbs;
    }
    public Autorisationabsence(String numDemAbs, Typeabsence typeabsence, Agent agent, Date dateDem, Date dateDebutAbs, Date dateFinAbs, Date dateRetourEff, String commentaire, Set agtraitedemabses) {
       this.numDemAbs = numDemAbs;
       this.typeabsence = typeabsence;
       this.agent = agent;
       this.dateDem = dateDem;
       this.dateDebutAbs = dateDebutAbs;
       this.dateFinAbs = dateFinAbs;
       this.dateRetourEff = dateRetourEff;
       this.commentaire = commentaire;
       this.agtraitedemabses = agtraitedemabses;
    }
   
    public String getNumDemAbs() {
        return this.numDemAbs;
    }
    
    public void setNumDemAbs(String numDemAbs) {
        this.numDemAbs = numDemAbs;
    }
    public Typeabsence getTypeabsence() {
        return this.typeabsence;
    }
    
    public void setTypeabsence(Typeabsence typeabsence) {
        this.typeabsence = typeabsence;
    }
    public Agent getAgent() {
        return this.agent;
    }
    
    public void setAgent(Agent agent) {
        this.agent = agent;
    }
    public Date getDateDem() {
        return this.dateDem;
    }
    
    public void setDateDem(Date dateDem) {
        this.dateDem = dateDem;
    }
    public Date getDateDebutAbs() {
        return this.dateDebutAbs;
    }
    
    public void setDateDebutAbs(Date dateDebutAbs) {
        this.dateDebutAbs = dateDebutAbs;
    }
    public Date getDateFinAbs() {
        return this.dateFinAbs;
    }
    
    public void setDateFinAbs(Date dateFinAbs) {
        this.dateFinAbs = dateFinAbs;
    }
    public Date getDateRetourEff() {
        return this.dateRetourEff;
    }
    
    public void setDateRetourEff(Date dateRetourEff) {
        this.dateRetourEff = dateRetourEff;
    }
    public String getCommentaire() {
        return this.commentaire;
    }
    
    public void setCommentaire(String commentaire) {
        this.commentaire = commentaire;
    }
    public Set getAgtraitedemabses() {
        return this.agtraitedemabses;
    }
    
    public void setAgtraitedemabses(Set agtraitedemabses) {
        this.agtraitedemabses = agtraitedemabses;
    }




}


