package pojoandmapping;
// Generated 23 juin 2014 16:20:08 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Direction generated by hbm2java
 */
public class Direction  implements java.io.Serializable {


     private String codeDirect;
     private String nomDirect;
     private Set services = new HashSet(0);

    public Direction() {
    }

	
    public Direction(String codeDirect) {
        this.codeDirect = codeDirect;
    }
    public Direction(String codeDirect, String nomDirect, Set services) {
       this.codeDirect = codeDirect;
       this.nomDirect = nomDirect;
       this.services = services;
    }
   
    public String getCodeDirect() {
        return this.codeDirect;
    }
    
    public void setCodeDirect(String codeDirect) {
        this.codeDirect = codeDirect;
    }
    public String getNomDirect() {
        return this.nomDirect;
    }
    
    public void setNomDirect(String nomDirect) {
        this.nomDirect = nomDirect;
    }
    public Set getServices() {
        return this.services;
    }
    
    public void setServices(Set services) {
        this.services = services;
    }




}


