package pojoandmapping;
// Generated 23 juin 2014 16:20:08 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Piecesjustif generated by hbm2java
 */
public class Piecesjustif  implements java.io.Serializable {


     private String idPiece;
     private String nomPiece;
     private Boolean typeFormat;
     private Set typecongePjs = new HashSet(0);

    public Piecesjustif() {
    }

	
    public Piecesjustif(String idPiece) {
        this.idPiece = idPiece;
    }
    public Piecesjustif(String idPiece, String nomPiece, Boolean typeFormat, Set typecongePjs) {
       this.idPiece = idPiece;
       this.nomPiece = nomPiece;
       this.typeFormat = typeFormat;
       this.typecongePjs = typecongePjs;
    }
   
    public String getIdPiece() {
        return this.idPiece;
    }
    
    public void setIdPiece(String idPiece) {
        this.idPiece = idPiece;
    }
    public String getNomPiece() {
        return this.nomPiece;
    }
    
    public void setNomPiece(String nomPiece) {
        this.nomPiece = nomPiece;
    }
    public Boolean getTypeFormat() {
        return this.typeFormat;
    }
    
    public void setTypeFormat(Boolean typeFormat) {
        this.typeFormat = typeFormat;
    }
    public Set getTypecongePjs() {
        return this.typecongePjs;
    }
    
    public void setTypecongePjs(Set typecongePjs) {
        this.typecongePjs = typecongePjs;
    }




}


