package pojoandmapping;
// Generated 23 juin 2014 16:20:08 by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Sabsente generated by hbm2java
 */
public class Sabsente  implements java.io.Serializable {


     private SabsenteId id;
     private Absenceshebdo absenceshebdo;
     private Agent agent;
     private Integer nbJour;
     private Date motifGeneral;
     private Boolean motifValable;
     private Integer nbJourDeduct;

    public Sabsente() {
    }

	
    public Sabsente(SabsenteId id, Absenceshebdo absenceshebdo, Agent agent) {
        this.id = id;
        this.absenceshebdo = absenceshebdo;
        this.agent = agent;
    }
    public Sabsente(SabsenteId id, Absenceshebdo absenceshebdo, Agent agent, Integer nbJour, Date motifGeneral, Boolean motifValable, Integer nbJourDeduct) {
       this.id = id;
       this.absenceshebdo = absenceshebdo;
       this.agent = agent;
       this.nbJour = nbJour;
       this.motifGeneral = motifGeneral;
       this.motifValable = motifValable;
       this.nbJourDeduct = nbJourDeduct;
    }
   
    public SabsenteId getId() {
        return this.id;
    }
    
    public void setId(SabsenteId id) {
        this.id = id;
    }
    public Absenceshebdo getAbsenceshebdo() {
        return this.absenceshebdo;
    }
    
    public void setAbsenceshebdo(Absenceshebdo absenceshebdo) {
        this.absenceshebdo = absenceshebdo;
    }
    public Agent getAgent() {
        return this.agent;
    }
    
    public void setAgent(Agent agent) {
        this.agent = agent;
    }
    public Integer getNbJour() {
        return this.nbJour;
    }
    
    public void setNbJour(Integer nbJour) {
        this.nbJour = nbJour;
    }
    public Date getMotifGeneral() {
        return this.motifGeneral;
    }
    
    public void setMotifGeneral(Date motifGeneral) {
        this.motifGeneral = motifGeneral;
    }
    public Boolean getMotifValable() {
        return this.motifValable;
    }
    
    public void setMotifValable(Boolean motifValable) {
        this.motifValable = motifValable;
    }
    public Integer getNbJourDeduct() {
        return this.nbJourDeduct;
    }
    
    public void setNbJourDeduct(Integer nbJourDeduct) {
        this.nbJourDeduct = nbJourDeduct;
    }




}


