package pojoandmapping;
// Generated 23 juin 2014 16:20:08 by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * SabsenteId generated by hbm2java
 */
public class SabsenteId  implements java.io.Serializable {


     private String matricAg;
     private Date dateDebut;
     private String periode;

    public SabsenteId() {
    }

    public SabsenteId(String matricAg, Date dateDebut, String periode) {
       this.matricAg = matricAg;
       this.dateDebut = dateDebut;
       this.periode = periode;
    }
   
    public String getMatricAg() {
        return this.matricAg;
    }
    
    public void setMatricAg(String matricAg) {
        this.matricAg = matricAg;
    }
    public Date getDateDebut() {
        return this.dateDebut;
    }
    
    public void setDateDebut(Date dateDebut) {
        this.dateDebut = dateDebut;
    }
    public String getPeriode() {
        return this.periode;
    }
    
    public void setPeriode(String periode) {
        this.periode = periode;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof SabsenteId) ) return false;
		 SabsenteId castOther = ( SabsenteId ) other; 
         
		 return ( (this.getMatricAg()==castOther.getMatricAg()) || ( this.getMatricAg()!=null && castOther.getMatricAg()!=null && this.getMatricAg().equals(castOther.getMatricAg()) ) )
 && ( (this.getDateDebut()==castOther.getDateDebut()) || ( this.getDateDebut()!=null && castOther.getDateDebut()!=null && this.getDateDebut().equals(castOther.getDateDebut()) ) )
 && ( (this.getPeriode()==castOther.getPeriode()) || ( this.getPeriode()!=null && castOther.getPeriode()!=null && this.getPeriode().equals(castOther.getPeriode()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getMatricAg() == null ? 0 : this.getMatricAg().hashCode() );
         result = 37 * result + ( getDateDebut() == null ? 0 : this.getDateDebut().hashCode() );
         result = 37 * result + ( getPeriode() == null ? 0 : this.getPeriode().hashCode() );
         return result;
   }   


}


