package pojoandmapping;
// Generated 23 juin 2014 16:20:08 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Semaine generated by hbm2java
 */
public class Semaine  implements java.io.Serializable {


     private Date dateDebut;
     private Date dateFin;
     private Set absenceshebdos = new HashSet(0);

    public Semaine() {
    }

	
    public Semaine(Date dateDebut) {
        this.dateDebut = dateDebut;
    }
    public Semaine(Date dateDebut, Date dateFin, Set absenceshebdos) {
       this.dateDebut = dateDebut;
       this.dateFin = dateFin;
       this.absenceshebdos = absenceshebdos;
    }
   
    public Date getDateDebut() {
        return this.dateDebut;
    }
    
    public void setDateDebut(Date dateDebut) {
        this.dateDebut = dateDebut;
    }
    public Date getDateFin() {
        return this.dateFin;
    }
    
    public void setDateFin(Date dateFin) {
        this.dateFin = dateFin;
    }
    public Set getAbsenceshebdos() {
        return this.absenceshebdos;
    }
    
    public void setAbsenceshebdos(Set absenceshebdos) {
        this.absenceshebdos = absenceshebdos;
    }




}


