package pojoandmapping;
// Generated 23 juin 2014 16:20:08 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Statut generated by hbm2java
 */
public class Statut  implements java.io.Serializable {


     private int idStatut;
     private Integer grade;
     private Integer echelon;
     private Integer salaire;
     private Set agents = new HashSet(0);

    public Statut() {
    }

	
    public Statut(int idStatut) {
        this.idStatut = idStatut;
    }
    public Statut(int idStatut, Integer grade, Integer echelon, Integer salaire, Set agents) {
       this.idStatut = idStatut;
       this.grade = grade;
       this.echelon = echelon;
       this.salaire = salaire;
       this.agents = agents;
    }
   
    public int getIdStatut() {
        return this.idStatut;
    }
    
    public void setIdStatut(int idStatut) {
        this.idStatut = idStatut;
    }
    public Integer getGrade() {
        return this.grade;
    }
    
    public void setGrade(Integer grade) {
        this.grade = grade;
    }
    public Integer getEchelon() {
        return this.echelon;
    }
    
    public void setEchelon(Integer echelon) {
        this.echelon = echelon;
    }
    public Integer getSalaire() {
        return this.salaire;
    }
    
    public void setSalaire(Integer salaire) {
        this.salaire = salaire;
    }
    public Set getAgents() {
        return this.agents;
    }
    
    public void setAgents(Set agents) {
        this.agents = agents;
    }




}


