package pojoandmapping;
// Generated 23 juin 2014 16:20:08 by Hibernate Tools 3.2.1.GA



/**
 * TypecongePjId generated by hbm2java
 */
public class TypecongePjId  implements java.io.Serializable {


     private String idPiece;
     private String codeTypeConge;

    public TypecongePjId() {
    }

    public TypecongePjId(String idPiece, String codeTypeConge) {
       this.idPiece = idPiece;
       this.codeTypeConge = codeTypeConge;
    }
   
    public String getIdPiece() {
        return this.idPiece;
    }
    
    public void setIdPiece(String idPiece) {
        this.idPiece = idPiece;
    }
    public String getCodeTypeConge() {
        return this.codeTypeConge;
    }
    
    public void setCodeTypeConge(String codeTypeConge) {
        this.codeTypeConge = codeTypeConge;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof TypecongePjId) ) return false;
		 TypecongePjId castOther = ( TypecongePjId ) other; 
         
		 return ( (this.getIdPiece()==castOther.getIdPiece()) || ( this.getIdPiece()!=null && castOther.getIdPiece()!=null && this.getIdPiece().equals(castOther.getIdPiece()) ) )
 && ( (this.getCodeTypeConge()==castOther.getCodeTypeConge()) || ( this.getCodeTypeConge()!=null && castOther.getCodeTypeConge()!=null && this.getCodeTypeConge().equals(castOther.getCodeTypeConge()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getIdPiece() == null ? 0 : this.getIdPiece().hashCode() );
         result = 37 * result + ( getCodeTypeConge() == null ? 0 : this.getCodeTypeConge().hashCode() );
         return result;
   }   


}


