package pojoandmapping;
// Generated 23 juin 2014 16:20:08 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Typeconge generated by hbm2java
 */
public class Typeconge  implements java.io.Serializable {


     private String codeTypeConge;
     private String nomTypeConge;
     private Integer nbJrMaxConge;
     private Set typecongePjs = new HashSet(0);
     private Set conges = new HashSet(0);

    public Typeconge() {
    }

	
    public Typeconge(String codeTypeConge) {
        this.codeTypeConge = codeTypeConge;
    }
    public Typeconge(String codeTypeConge, String nomTypeConge, Integer nbJrMaxConge, Set typecongePjs, Set conges) {
       this.codeTypeConge = codeTypeConge;
       this.nomTypeConge = nomTypeConge;
       this.nbJrMaxConge = nbJrMaxConge;
       this.typecongePjs = typecongePjs;
       this.conges = conges;
    }
   
    public String getCodeTypeConge() {
        return this.codeTypeConge;
    }
    
    public void setCodeTypeConge(String codeTypeConge) {
        this.codeTypeConge = codeTypeConge;
    }
    public String getNomTypeConge() {
        return this.nomTypeConge;
    }
    
    public void setNomTypeConge(String nomTypeConge) {
        this.nomTypeConge = nomTypeConge;
    }
    public Integer getNbJrMaxConge() {
        return this.nbJrMaxConge;
    }
    
    public void setNbJrMaxConge(Integer nbJrMaxConge) {
        this.nbJrMaxConge = nbJrMaxConge;
    }
    public Set getTypecongePjs() {
        return this.typecongePjs;
    }
    
    public void setTypecongePjs(Set typecongePjs) {
        this.typecongePjs = typecongePjs;
    }
    public Set getConges() {
        return this.conges;
    }
    
    public void setConges(Set conges) {
        this.conges = conges;
    }




}


