package pojoandmapping;
// Generated 23 juin 2014 16:20:08 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Typeabsence generated by hbm2java
 */
public class Typeabsence  implements java.io.Serializable {


     private String codeTypeAbs;
     private String nomAbs;
     private Integer nbJrMax;
     private Boolean absDeduct;
     private Set autorisationabsences = new HashSet(0);

    public Typeabsence() {
    }

	
    public Typeabsence(String codeTypeAbs) {
        this.codeTypeAbs = codeTypeAbs;
    }
    public Typeabsence(String codeTypeAbs, String nomAbs, Integer nbJrMax, Boolean absDeduct, Set autorisationabsences) {
       this.codeTypeAbs = codeTypeAbs;
       this.nomAbs = nomAbs;
       this.nbJrMax = nbJrMax;
       this.absDeduct = absDeduct;
       this.autorisationabsences = autorisationabsences;
    }
   
    public String getCodeTypeAbs() {
        return this.codeTypeAbs;
    }
    
    public void setCodeTypeAbs(String codeTypeAbs) {
        this.codeTypeAbs = codeTypeAbs;
    }
    public String getNomAbs() {
        return this.nomAbs;
    }
    
    public void setNomAbs(String nomAbs) {
        this.nomAbs = nomAbs;
    }
    public Integer getNbJrMax() {
        return this.nbJrMax;
    }
    
    public void setNbJrMax(Integer nbJrMax) {
        this.nbJrMax = nbJrMax;
    }
    public Boolean getAbsDeduct() {
        return this.absDeduct;
    }
    
    public void setAbsDeduct(Boolean absDeduct) {
        this.absDeduct = absDeduct;
    }
    public Set getAutorisationabsences() {
        return this.autorisationabsences;
    }
    
    public void setAutorisationabsences(Set autorisationabsences) {
        this.autorisationabsences = autorisationabsences;
    }




}


